// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Appointment struct {
	ID              int32     `json:"id"`
	CustomerID      int32     `json:"customer_id"`
	AppointmentDate time.Time `json:"appointment_date"`
	ServiceName     string    `json:"service_name"`
}

type Customer struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
