// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (customer_id, appointment_date, service_name) VALUES ($1, $2, $3) RETURNING id, customer_id, appointment_date, service_name
`

type CreateAppointmentParams struct {
	CustomerID      int32     `json:"customer_id"`
	AppointmentDate time.Time `json:"appointment_date"`
	ServiceName     string    `json:"service_name"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRowContext(ctx, createAppointment, arg.CustomerID, arg.AppointmentDate, arg.ServiceName)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.AppointmentDate,
		&i.ServiceName,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, email) VALUES ($1, $2) RETURNING id, name, email
`

type CreateCustomerParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer, arg.Name, arg.Email)
	var i Customer
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash) VALUES ($1, $2) RETURNING id, email, password_hash, refresh_token, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RefreshToken,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCustomer, id)
	return err
}

const getCustomerWithAppointmentsNested = `-- name: GetCustomerWithAppointmentsNested :one
SELECT 
    c.id, c.name, c.email,
    COALESCE(json_agg(
        json_build_object(
            'id', a.id,
            'appointment_date', a.appointment_date,
            'service_name', a.service_name
        )
    ) FILTER (WHERE a.id IS NOT NULL), '[]')::json AS appointments
FROM customers c
LEFT JOIN appointments a ON c.id = a.customer_id
WHERE c.id = $1
GROUP BY c.id
`

type GetCustomerWithAppointmentsNestedRow struct {
	ID           int32           `json:"id"`
	Name         string          `json:"name"`
	Email        string          `json:"email"`
	Appointments json.RawMessage `json:"appointments"`
}

func (q *Queries) GetCustomerWithAppointmentsNested(ctx context.Context, id int32) (GetCustomerWithAppointmentsNestedRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerWithAppointmentsNested, id)
	var i GetCustomerWithAppointmentsNestedRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Appointments,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, refresh_token, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.RefreshToken,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, email FROM customers ORDER BY id
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers SET name = $2, email = $3 WHERE id = $1
`

type UpdateCustomerParams struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomer, arg.ID, arg.Name, arg.Email)
	return err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE users SET refresh_token = $2 WHERE id = $1
`

type UpdateRefreshTokenParams struct {
	ID           int32          `json:"id"`
	RefreshToken sql.NullString `json:"refresh_token"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshToken, arg.ID, arg.RefreshToken)
	return err
}
